openapi: '3.0.2'
info:
  title: Datastandaard fietsparkeren
  version: '1.0'
security: []
servers:
  - url: https://api.server.test/v1
components:
  securitySchemes:
    "api_key":
      type: apiKey
      name: Implementation-specific API access control
      in: header
  schemas:
    Survey:
      title: Survey
      description: An investigation of data collection, incidentally or continiously on behalf of a client by a contractor.
      type: object
      required:
        - "name"
        - "authority"
        - "contractors"
      properties:
        id:
            $ref: '#/components/schemas/ResourceIdentifier'
        name: 
          type: string
          description: Title of the survey
        authority:
          type: string
          description: "{{Organisation.id}} of the client."
        contractors:
          type: array
          items:
            type: string
            description: "{{Organisation.id}} of the contractor."
        license: 
          type: string
          description: License for using the data (reference or text).
        surveyAreas:
          type: array
          items:
            type: string
            description: Survey areas contained.
        distinguishesVehicleCategories:
          type: array
          items:
            $ref: '#/components/schemas/CanonicalVehicle'
    Organisation:
      type: object
      title: Organisation
      required:
        - "name"
      properties:
        id:
            $ref: '#/components/schemas/ResourceIdentifier'
        name: 
          type: string
          description: Name of the organisation
    SurveyArea:
      type: object
      title: SurveyArea
    ParkingFacility:
      type: object
      title: Parking facility
    Section:
      type: object
      title: Section
    ParkingSpaceType:
      type: object
      title: Parking space type
    Observation:
      type: object
      title: Observation
    CapacityMeasurement:
      type: object
      title: Capactiy measurement
    OccupationMeasurement:
      type: object
      title: Occupation measurement
    CapacityPerParkingSpaceType:
      type: object
      title: .
    VehicleTypeCount:
      type: object
      title: .
    Note:
      type: object
      title: ...
    Vehicle: 
      type: object
      title: ....
    CanonicalVehicle:
      type: object
      title: CanonicalVehicle
    Accessory:
      type: object
      title: Accessory
    VehicleState:
      type: object
      title: VehicleState
    ResourceIdentifier:
      type: string
      description: A unique identifier.
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
